Use V1 resolver as publishes seem to fail with…
…

```
error: failed to prepare local package for uploading

Caused by:
  values must be emitted before tables
```